### ISSUE TITLE
 Undefined index: banner

### ISSUE THREAD

**Issue by fjhadz1** [Athlon1600/SerpScraper#6]
Hi,
I'm currently having problem with this every time I've encountered a captcha.
just to add I do have deathbycaptcha account.

 Notice: Undefined index: banner in C:\wamp\www\newathlon\vendor\athlon1600\serpscraper\src\Captcha\dbc_api.php on line 801

Thanks.

**Comment by Athlon1600** [comment]
That's actually the problem with the code from DeathByCaptcha people themselves. I didn't write that API, that came from them. So when they need fix it, I'll update it here. I'd rather not try and fix it myself because I don't know how their stuff works. Either way, captcha solving works, that warning is meaningless and I would just ignore it like this:

``` php
@$google->solveCaptcha($dbc);
```

**Comment by fjhadz1** [comment]
Thanks Athlon. Hope they will fix the problem soon. I added already the line and it works in ignoring the warning. 

I really appreciate your work. Thanks once again.
